// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// UItest1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfEdit uITBEdit = this.UIMyCalculatorv1Window.UITBEdit;
            WpfButton uIItem5Button = this.UIMyCalculatorv1Window.UIItem5Button;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            WpfButton uIItem0Button = this.UIMyCalculatorv1Window.UIItem0Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            WpfButton uIItem1Button = this.UIMyCalculatorv1Window.UIItem1Button;
            WpfButton uIItemButton2 = this.UIMyCalculatorv1Window.UIItemButton2;
            WinButton uICloseButton = this.UIInternetDownloadManaWindow.UIInternetDownloadManaTitleBar.UICloseButton;
            WpfButton uIItemButton3 = this.UIMyCalculatorv1Window.UIItemButton3;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton4 = this.UIMyCalculatorv1Window.UIItemButton4;
            #endregion

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(15, 14));

            // Type '' in 'tb' text box
            uITBEdit.Text = this.RecordedMethod1Params.UITBEditText;

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(30, 24));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(29, 15));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(29, 6));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(35, 13));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(32, 10));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(27, 18));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(27, 13));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(33, 13));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(38, 20));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(24, 14));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(16, 23));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(28, 26));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(30, 23));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(33, 15));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(36, 17));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(25, 10));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(57, 14));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(18, 14));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(18, 7));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(21, 8));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(24, 4));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(26, 16));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(56, 12));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(31, 9));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(24, 14));

            // Click '-' button
            Mouse.Click(uIItemButton2, new Point(27, 19));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(25, 21));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(59, 3));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(35, 10));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(28, 12));

            // Click '-' button
            Mouse.Click(uIItemButton2, new Point(29, 14));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(26, 16));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(49, 10));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(20, 21));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(30, 12));

            // Click '-' button
            Mouse.Click(uIItemButton2, new Point(34, 17));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(13, 12));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(44, 13));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(15, 10));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(26, 14));

            // Click '-' button
            Mouse.Click(uIItemButton2, new Point(23, 7));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(27, 6));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(29, 4));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(50, 9));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(33, 7));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(65, 17));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(27, 18));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(28, 8));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(33, 6));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(21, 13));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(55, 24));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(2, 11));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(26, 16));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(26, 20));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(25, 22));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(38, 13));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(13, 8));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(31, 11));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(19, 11));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(31, 17));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(31, 9));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(31, 9));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(14, 14));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(29, 11));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(28, 7));

            // Click '-' button
            Mouse.Click(uIItemButton2, new Point(34, 9));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(21, 7));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(56, 9));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(32, 9));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(27, 11));

            // Click '/' button
            Mouse.Click(uIItemButton4, new Point(32, 19));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(15, 23));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(18, 18));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(11, 12));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(18, 9));

            // Click '/' button
            Mouse.Click(uIItemButton4, new Point(31, 20));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(29, 11));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(59, 23));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(27, 20));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(21, 16));

            // Click '/' button
            Mouse.Click(uIItemButton4, new Point(26, 16));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(18, 16));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(37, 13));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(9, 13));

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(31, 17));

            // Click '/' button
            Mouse.Click(uIItemButton4, new Point(38, 14));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(27, 8));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(11, 10));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(63, 10));
        }
        
        /// <summary>
        /// testing method plus
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            WpfButton uIItem1Button = this.UIMyCalculatorv1Window.UIItem1Button;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(24, 9));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(20, 13));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(23, 4));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(8, 23));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(24, 7));

            // Move '+' button to '1' button
            uIItem1Button.EnsureClickable(new Point(20, 11));
            Mouse.StartDragging(uIItemButton, new Point(29, 10));
            Mouse.StopDragging(uIItem1Button, new Point(20, 11));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(22, 9));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(23, 12));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(45, 18));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(10, 8));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UIMyCalculatorv1Window UIMyCalculatorv1Window
        {
            get
            {
                if ((this.mUIMyCalculatorv1Window == null))
                {
                    this.mUIMyCalculatorv1Window = new UIMyCalculatorv1Window();
                }
                return this.mUIMyCalculatorv1Window;
            }
        }
        
        public UIInternetDownloadManaWindow UIInternetDownloadManaWindow
        {
            get
            {
                if ((this.mUIInternetDownloadManaWindow == null))
                {
                    this.mUIInternetDownloadManaWindow = new UIInternetDownloadManaWindow();
                }
                return this.mUIInternetDownloadManaWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UIMyCalculatorv1Window mUIMyCalculatorv1Window;
        
        private UIInternetDownloadManaWindow mUIInternetDownloadManaWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type '' in 'tb' text box
        /// </summary>
        public string UITBEditText = "";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIMyCalculatorv1Window : WpfWindow
    {
        
        public UIMyCalculatorv1Window()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MyCalculator v1";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MyCalculator v1");
            #endregion
        }
        
        #region Properties
        public WpfButton UIDelButton
        {
            get
            {
                if ((this.mUIDelButton == null))
                {
                    this.mUIDelButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIDelButton.SearchProperties[WpfButton.PropertyNames.Name] = "Del";
                    this.mUIDelButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIDelButton;
            }
        }
        
        public WpfEdit UITBEdit
        {
            get
            {
                if ((this.mUITBEdit == null))
                {
                    this.mUITBEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITBEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "tb";
                    this.mUITBEdit.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUITBEdit;
            }
        }
        
        public WpfButton UIItem5Button
        {
            get
            {
                if ((this.mUIItem5Button == null))
                {
                    this.mUIItem5Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem5Button.SearchProperties[WpfButton.PropertyNames.Name] = "5";
                    this.mUIItem5Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem5Button;
            }
        }
        
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WpfButton.PropertyNames.Name] = "+";
                    this.mUIItemButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WpfButton UIItem0Button
        {
            get
            {
                if ((this.mUIItem0Button == null))
                {
                    this.mUIItem0Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem0Button.SearchProperties[WpfButton.PropertyNames.Name] = "0";
                    this.mUIItem0Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem0Button;
            }
        }
        
        public WpfButton UIItemButton1
        {
            get
            {
                if ((this.mUIItemButton1 == null))
                {
                    this.mUIItemButton1 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton1.SearchProperties[WpfButton.PropertyNames.Name] = "=";
                    this.mUIItemButton1.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton1;
            }
        }
        
        public WpfButton UIItem1Button
        {
            get
            {
                if ((this.mUIItem1Button == null))
                {
                    this.mUIItem1Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem1Button.SearchProperties[WpfButton.PropertyNames.Name] = "1";
                    this.mUIItem1Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem1Button;
            }
        }
        
        public WpfButton UIItemButton2
        {
            get
            {
                if ((this.mUIItemButton2 == null))
                {
                    this.mUIItemButton2 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton2.SearchProperties[WpfButton.PropertyNames.Name] = "-";
                    this.mUIItemButton2.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton2;
            }
        }
        
        public WpfButton UIItemButton3
        {
            get
            {
                if ((this.mUIItemButton3 == null))
                {
                    this.mUIItemButton3 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton3.SearchProperties[WpfButton.PropertyNames.Name] = "*";
                    this.mUIItemButton3.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton3;
            }
        }
        
        public WpfButton UIItem2Button
        {
            get
            {
                if ((this.mUIItem2Button == null))
                {
                    this.mUIItem2Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem2Button.SearchProperties[WpfButton.PropertyNames.Name] = "2";
                    this.mUIItem2Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem2Button;
            }
        }
        
        public WpfButton UIItemButton4
        {
            get
            {
                if ((this.mUIItemButton4 == null))
                {
                    this.mUIItemButton4 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton4.SearchProperties[WpfButton.PropertyNames.Name] = "/";
                    this.mUIItemButton4.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton4;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIDelButton;
        
        private WpfEdit mUITBEdit;
        
        private WpfButton mUIItem5Button;
        
        private WpfButton mUIItemButton;
        
        private WpfButton mUIItem0Button;
        
        private WpfButton mUIItemButton1;
        
        private WpfButton mUIItem1Button;
        
        private WpfButton mUIItemButton2;
        
        private WpfButton mUIItemButton3;
        
        private WpfButton mUIItem2Button;
        
        private WpfButton mUIItemButton4;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIInternetDownloadManaWindow : WinWindow
    {
        
        public UIInternetDownloadManaWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Internet Download Manager";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Internet Download Manager");
            #endregion
        }
        
        #region Properties
        public UIInternetDownloadManaTitleBar UIInternetDownloadManaTitleBar
        {
            get
            {
                if ((this.mUIInternetDownloadManaTitleBar == null))
                {
                    this.mUIInternetDownloadManaTitleBar = new UIInternetDownloadManaTitleBar(this);
                }
                return this.mUIInternetDownloadManaTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIInternetDownloadManaTitleBar mUIInternetDownloadManaTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIInternetDownloadManaTitleBar : WinTitleBar
    {
        
        public UIInternetDownloadManaTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Internet Download Manager");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Internet Download Manager");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
}
